loadSequentially('Scenes/',
[
  "Scene.js",
  "GameScene.js",
  "MenuScene.js",
  "IntroScene.js",
  "PigFunScene.js",
  "PauseScene.js",
  "WinScene.js",
  "LevelTesterScene.js",
  "LevelEditorScene.js",
]);