loadSequentially('Blocks/',
[
  "blockmanager.js",
  "groundBlock.js",
  "spikeBlock.js",
  "groundspikeBlock.js",
  "startBlock.js",
  "endBlock.js",
  "enemyBlock.js",
  "walljumpPowerup.js",
  "doublejumpPowerup.js",
]);