loadSequentially('Worlds/levels/',
[
  "init.js",
  "simpleJumpLevel.js",
  "longJumpLevel.js",
  "spikeyIslandsLevel.js",
  "justTheBirds.js",
  "woofPen.js",
  "needle.js",
  "subWoofer.js",
  "birdAndHay.js",
  "wallJumpTest.js",
  "multiPathing.js",
  "crescentDeth.js",
  // "level1.js",
  // "level2.js",
  // "level3.js",
  // "level4.js",
  "level5.js",
  // "levelx.js",
]
);