loadSequentially('Worlds/levels/',
[
  "init.js",
  // "level1.js",
  // "level2.js",
  "simpleJumpLevel.js",
  "longJumpLevel.js",
  "justTheBirds.js",
  "woofPen.js",
  "level3.js",
  "wallJumpTest.js",
  "level4.js",
  "needle.js",
  "decisionPlatforming.js",
  // "subWoofer.js",
  "birdAndHay.js",
  "spikeyIslandsLevel.js",
  "nest.js",
  "woofBouncing.js",
  "multiPathing.js",
  // "crescentDeth.js",
  
  "level5.js",
  "HelltheThird.js",
  // "levelx.js",
]
);