loadSequentially('Levels/',
[
  "init.js",
  "simpleJumpLevel.js",
  "jumpChallenges.js",
  "needle.js",
  "woofPen.js",
  "LetTheDogsOut.js",
  "Roundabout.js",
  // "longJumpLevel.js",
  "justTheBirds.js",
  "wallJumpTest.js",
  "level4.js",
  "level3.js",
  "FloatingFeathers.js",
  "multiPathing.js",
  // "decisionPlatforming.js",
  // "birdAndHay.js",
  "woofRUN.js",
  "spikeyIslandsLevel.js",
  "deadlyByrds.js",
  "nest.js",
  "woofBouncing.js",
  // "crescentDeth.js",
  
  "level5.js",
  "knifeTest.js",
  // "HelltheThird.js",
  // "levelx.js",
]
);