loadSequentially('Levels/',
[
  "init.js",
  //"simpleJumpLevel.js",
  "jumpChallenges.js",
  // "needle.js",
  "woofPen.js",
  "LetTheDogsOut.js",
  "woofRUN.js",
  // "longJumpLevel.js",
  // "Roundabout.js",
  
  "TheAcorn2.js",
  "level4.js",
  "wallJumpTest.js",
  "AcornTactics.js",

  // "multiPathing.js",
  // "decisionPlatforming.js",
  // "birdAndHay.js",
  // "spikeyIslandsLevel.js",
  "justTheBirds.js",
  "nest.js",
  "woofBouncing.js",
  "level3.js",
  // "FloatingFeathers.js",
  "Bridge.js",
  "FeatherAdventure.js",
  "spikeTops.js",
  "deadlyByrds.js",
  // "crescentDeth.js",
  
  "level5.js",
  "knifeTest.js",
  // "HelltheThird.js",
  // "levelx.js",
]
);